<?php
/*
   Calendar tooltips module for Drupal.
   Ronald Baljeu (rjb@xs4all.nl)
   http://linuxpc.info/
*/

/* TODO: hook_uninstall() in order to remove setting variables */

/* Override the theme function template_preprocess_calendar_datebox() in
   modules/calendar/theme/theme.inc.
   See http://www.lullabot.com/articles/overriding-theme-functions-in-modules
   for more info on how to override theme functions in modules.

   Also register our init function for beautytips. We do not use hook_init()
   for this because older versions of beautytips_add_beautytips() called theme()
   which should not be called in hook_init(). In D6 this causes theming issues.
   See: http://drupal.org/node/219910. Workaround found at:
   http://drupal.org/node/599106.
*/
function hipic_boletes_calendari_theme_registry_alter(&$theme_registry) {
  if (!empty($theme_registry['preprocess_calendar_datebox'])) {
    $theme_registry['preprocess_calendar_datebox']['function'] =
      'hipic_boletes_calendari_preprocess_calendar_datebox';
  }
}

/**
 * Create the calendar date box.
 */
function hipic_boletes_calendari_preprocess_calendar_datebox(&$vars) {
  $date = $vars['date'];
  $view = $vars['view'];
  $vars['day'] = intval(substr($date, 8, 2));
  $force_view_url = !empty($view->date_info->block) ? TRUE : FALSE;
  $month_path = calendar_granularity_path($view, 'month');
  $year_path = calendar_granularity_path($view, 'year');
  $day_path = calendar_granularity_path($view, 'day');
  $vars['url'] = str_replace(array($month_path, $year_path), $day_path, date_pager_url($view, NULL, $date, $force_view_url));
//  $vars['link'] = !empty($day_path) ? l($vars['day'], 'calendario/'.$date) : $vars['day'];
  $vars['granularity'] = $view->date_info->granularity;
  $vars['mini'] = !empty($view->date_info->mini);

  /* AFEGIT ALEX PER PRESENTAR BOLETES 
		màxim 3 boletes
		no repeteix colors 	
  */
  $tids=array();
  if (!empty($vars['selected'])) {
    $bt_text = "<br/>";
    foreach ($vars['items'][$date] as $time => $results_at_that_time) { //per cada DIA
      foreach ($results_at_that_time as $num => $result) { //PER CADA EVENT
		if (count($tids)==3) break;
        $result = (array)$result;
		$tid=$result['rendered_fields']["tid"];
		if (in_array($tid,$tids)) continue;
		$tids[]=(int)$tid;
        $bt_text .= "<div class=\"evento-bolita evento-bolita-calendari evento-bolita-".$tid."\"/>";
     }
    }
    $vars['link'] .= $bt_text;
    $vars['link']=str_replace("calendar-node-field-event-date/day/","calendario/",$vars['link']);
	
    /*
       The balloon text is appended to the link variable,
       like this: "<a href=...>31</a> <div>balloon text</div>" (see above).
       which makes it difficult for the user to alter the link without
       losing the balloon text. That's why we provide an extra variable with
       the balloon text only. The user may use this to append to
       the new link when overriding calendar-datebox.tpl.php.
    */
    $vars['calendar_tooltips_text'] = $bt_text;
  }
  /* End of additional code. */

  if ($vars['mini']) {
    if (!empty($vars['selected'])) {
      $vars['class'] = 'mini-day-on';
    }
    else {
      $vars['class'] = 'mini-day-off';
    }
  }
  else {
    $vars['class'] = 'day';
  }
}
